(cl:defpackage jethexa_controller_interfaces-srv
  (:use )
  (:export
   "POSETRANSFORM"
   "<POSETRANSFORM-REQUEST>"
   "POSETRANSFORM-REQUEST"
   "<POSETRANSFORM-RESPONSE>"
   "POSETRANSFORM-RESPONSE"
   "SETPOSE1"
   "<SETPOSE1-REQUEST>"
   "SETPOSE1-REQUEST"
   "<SETPOSE1-RESPONSE>"
   "SETPOSE1-RESPONSE"
   "SETPOSE2"
   "<SETPOSE2-REQUEST>"
   "SETPOSE2-REQUEST"
   "<SETPOSE2-RESPONSE>"
   "SETPOSE2-RESPONSE"
   "SIMPLEMOVING"
   "<SIMPLEMOVING-REQUEST>"
   "SIMPLEMOVING-REQUEST"
   "<SIMPLEMOVING-RESPONSE>"
   "SIMPLEMOVING-RESPONSE"
  ))

